#!/usr/bin/env node
// Writes sw-precache.js: the complete list of app files the service worker
// installs as one release, plus a build id (a hash of their contents) that
// names the release cache. Run after any change to the shell:
//   npm run sw          write sw-precache.js
//   npm run sw -- --check   exit 1 when the committed file is stale (the unit suite does this)
// Maps, data and the worker API are not app files: maps come from the map
// route and live in IndexedDB, so the precache is the shell alone.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIRS = ['js', 'client', 'shared', 'styles', 'icons'];
const FILES = ['index.html', 'icons.svg', 'manifest.webmanifest'];

export function buildPrecache() {
  const files = [...FILES];
  const walk = d => { for (const e of fs.readdirSync(path.join(root, d), { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) { const p = `${d}/${e.name}`; if (e.isDirectory()) walk(p); else if (/\.(js|css|svg|png|webmanifest|json)$/.test(e.name)) files.push(p); } };
  for (const d of DIRS) walk(d);
  const h = crypto.createHash('sha256');
  for (const f of files) { h.update(f); h.update(fs.readFileSync(path.join(root, f))); }
  const version = (fs.readFileSync(path.join(root, 'js/version.js'), 'utf8').match(/'([^']+)'/) || [])[1] || '0';
  h.update(version);
  return { version, build: h.digest('hex').slice(0, 10), files: files.map(f => './' + f) };
}
export function render(p) {
  return `// Generated by scripts/build-sw.js. Do not hand-edit: run \`npm run sw\`.\n// The complete app shell for one release; the build id names its cache.\nself.PRECACHE = ${JSON.stringify(p, null, 2)};\n`;
}
if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const out = path.join(root, 'sw-precache.js');
  const next = render(buildPrecache());
  const cur = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
  if (process.argv.includes('--check')) { if (cur !== next) { console.error('sw-precache.js is stale: run npm run sw'); process.exit(1); } console.log('sw-precache.js is current'); }
  else { fs.writeFileSync(out, next); const p = buildPrecache(); console.log(`sw-precache.js: ${p.files.length} files, build ${p.build}, version ${p.version}`); }
}
